import type { Metadata } from "next";
import './globals.css'; // ← これを追加

export const metadata: Metadata = {
  title: "クラスメンバーCSVアプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
